name: flutter_template
description: "Flutter template"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  flutter_localization: ^0.2.0
  dio: ^5.4.3+1
  flutter_map: ^7.0.1
  fluttertoast: ^8.2.6
  camera: ^0.11.0+1
  path_provider: ^2.1.3
  path: ^1.9.0
  date_picker_plus: ^4.1.0
  geolocator: ^7.0.0
  geocoding: ^2.2.2
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - i18n/
